<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

?>
<div class="tema"><?php echo $tema; ?></div>

<?php
if ($notificacion) {
    echo $notificacion;
}
?>
<form class="pure-form pure-form-aligned" method="POST" > 
    <input type="hidden" value="<?php echo $_docente[0]["dni"]; ?>" name="dni_docente">
    <input type="hidden" value="<?php echo $_POST["pagina_referencia"] ;?>" name="pagina_referencia">
    <fieldset>
        <table class="pure-table pure-table-bordered" id="formulario">
            <thead>
                <tr>
                    <th colspan="2">
                        <label>Datos del Docente</label>
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <label  for="tipo_dni">Tipo de Documento</label>
                    </td>                      
                    <td>
                        <select id="tipo_dni" name="tipo_dni">
                            <option value="V" <?php if ($_docente[0]["tipo_dni"] == "V") { echo "selected"; }?>>V</option>
                            <option value="E" <?php if ($_docente[0]["tipo_dni"] == "E") { echo "selected"; }?>>E</option>
                        </select>
                        <span class='campo-obligatorio'>*</span>
                    </td>   
                </tr>  
                <tr>
                    <td>
                        <label for="dni">Documento de Identidad</label>
                    </td>                      
                    <td>
                        <input id="name" type="text" placeholder="Documento de Identidad" maxlength="8" name="dni" value="<?php echo $_docente[0]["dni"]; ?>" class="solo-numero-entero">
                        <span class='campo-obligatorio'>*</span>
                    </td>
                </tr>

                <tr>
                    <td>
                        <label for="nombre">Nombres</label>
                    </td>                      
                    <td>
                        <input type="text" placeholder="Nombres" maxlength="40" name="nombre" value="<?php echo $_docente[0]["nombre"]; ?>" class="solo-letras-con-espacio-y-acentos">
                        <span class='campo-obligatorio'>*</span>
                    </td>    
                </tr>

                <tr>
                    <td>
                        <label for="apellido">Apellidos</label>
                    </td>                      
                    <td>
                        <input type="text" placeholder="Apellidos" maxlength="40" name="apellido" value="<?php echo $_docente[0]["apellido"]; ?>" class="solo-letras-con-espacio-y-acentos">
                        <span class='campo-obligatorio'>*</span>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label  for="sexo">Sexo</label>
                    </td>                      
                    <td>
                        <select id="state" name="sexo">
                            <option value="Femenino" <?php if ($_docente[0]["sexo"] == "Femenino") { echo "selected"; }?>>Femenino</option>
                            <option value="Masculino" <?php if ($_docente[0]["sexo"] == "Masculino") { echo "selected"; }?>>Masculino</option>
                        </select>
                        <span class='campo-obligatorio'>*</span>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="cargo">Cargo</label>
                    </td>                      
                    <td>
                        <input type="text" placeholder="Cargo" name="cargo" maxlength="50" value="<?php echo $_docente[0]["cargo"]; ?>" class="solo-letras-con-espacio-y-acentos">
                        <span class='campo-obligatorio'>*</span>
                    </td>
                </tr>                 
                <tr>
                    <td>
                        <label for="fecha_natal">Fecha de Nacimiento</label>
                    </td>                      
                    <td>
                        <input type="text" placeholder="dd/mm/aaaa" name="fecha_natal" maxlength="10" value="<?php echo AsistenteBasico::convertirFechaDdMmAaaa($_docente[0]["fecha_natal"]); ?>" class="fecha" >
                        <span class='campo-obligatorio'>*</span>
                </td>
                </tr>       
                <tr>
                    <td colspan="2" align="center">
                            <input type="button" class="btn btn-primary" value="Cancelar" name="Salir" onClick="history.back();">
                            <input type="submit" class="btn btn-primary" value="Guardar" name="editar">
                    </td> 
                </tr>
            </tbody>    
        </table>    
    </fieldset>
</form>
