<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

?>
<div class="tema"><?php echo $tema; ?></div>

<?php
if ($notificacion) {
    echo $notificacion;
}
?>
<form class="pure-form pure-form-aligned" method="POST" > 
    <fieldset>
        <table class="pure-table pure-table-bordered" id="formulario">
            <thead>
                <tr>
                    <th colspan="2">
                        <label>Datos del Docente</label>
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <label  for="state">Tipo de Documento</label>
                    </td>                      
                    <td>
                        <select id="state" name="tipo_dni">
                            <option value="V" <?php if ($_POST["tipo_dni"] == "V") { echo "selected"; }?>>V</option>
                            <option value="E" <?php if ($_POST["tipo_dni"] == "E") { echo "selected"; }?>>E</option>
                        </select>
                        <span class='campo-obligatorio'>*</span>
                    </td>   
                </tr>  
                <tr>
                    <td>
                        <label for="name">Documento de Identidad</label>
                    </td>                      
                    <td>
                        <input id="name" type="text" placeholder="Documento de Identidad" maxlength="8" name="dni" value="<?php echo $_POST["dni"]; ?>" class="solo-numero-entero">
                        <span class='campo-obligatorio'>*</span>
                    </td>
                </tr>

                <tr>
                    <td>
                        <label for="password">Nombres</label>
                    </td>                      
                    <td>
                        <input type="text" placeholder="Nombres" maxlength="40" name="nombre" value="<?php echo $_POST["nombre"]; ?>" class="solo-letras-con-espacio-y-acentos">
                        <span class='campo-obligatorio'>*</span>
                    </td>    
                </tr>

                <tr>
                    <td>
                        <label for="password">Apellidos</label>
                    </td>                      
                    <td>
                        <input type="text" placeholder="Apellidos" maxlength="40" name="apellido" value="<?php echo $_POST["apellido"]; ?>" class="solo-letras-con-espacio-y-acentos">
                        <span class='campo-obligatorio'>*</span>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label  for="state">Sexo</label>
                    </td>                      
                    <td>
                        <select id="state" name="sexo">
                            <option value="Femenino" <?php if ($_POST["sexo"] == "Femenino") { echo "selected"; }?>>Femenino</option>
                            <option value="Masculino" <?php if ($_POST["sexo"] == "Masculino") { echo "selected"; }?>>Masculino</option>
                        </select>
                        <span class='campo-obligatorio'>*</span>
                    </td>
                </tr>     
                <tr>
                    <td>
                        <label for="email">Fecha de Nacimiento</label>
                    </td>                      
                    <td>
                        <input type="text" placeholder="dd/mm/aaaa" name="fecha_natal" maxlength="10" value="<?php echo $_POST["fecha_natal"]; ?>" class="fecha">
                        <span class='campo-obligatorio'>*</span>
                </td>
                </tr>
                <tr>
                    <td>
                        <label for="email">Cargo</label>
                    </td>                      
                    <td>
                        <input type="text" placeholder="Cargo" name="cargo" maxlength="50" value="<?php echo $_POST["cargo"]; ?>" class="solo-letras-con-espacio-y-acentos">
                        <span class='campo-obligatorio'>*</span>
                    </td>
                </tr>   
                
                <tr>
                    <td colspan="2" align="center">
                        <input type="button" class="btn btn-primary" value="Salir" onClick="window.location='<?php echo URLBASE; ?>inicio'">
                        <input type="submit" class="btn btn-primary" value="Registrar" name="registrar">
                    </td> 
                </tr>
            </tbody>    
        </table>    
    </fieldset>
</form>
