<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<script>
$(document).ready(function(){
   $("#semestre").change(function () {
       $("#semestre option:selected").each(function () {
            id = $(this).val();
            $.post("public/js/ajax/obtenerSeccionPorSemestre.php", { id: id }, function(data){
                $("#seccion").html(data);//Destino
            });            
        });
   })
});
</script>
<div class="tema"><?php echo $tema; ?></div>

<?php

if ($_periodo == 0):
    echo $notificacion;
else:
if ($notificacion) 
    echo $notificacion;
?>
<form class="pure-form pure-form-aligned" method="POST">
    <fieldset>
        <table class="pure-table pure-table-bordered" id="formulario">  
            <thead>
                <tr>
                    <th colspan="2">Datos para Registrar Extraordinario</th>
                </tr>
            </thead>
            <tbody>
                <tr>    
                    <td align="right">
                        <label for="name">Documento del Estudiante</label>
                    </td>
                    <td>
                        <input id="campo" type="text" placeholder="Documento de Identidad" maxlength="8" name="dni" value="<?php echo $_POST["dni"]; ?>" onKeyUp="autocompletadoEstudiante();" autocomplete="off">
                        <span class='campo-obligatorio'>*</span>
                         <ul id="lista_dni"></ul>
                    </td>         
                </tr>
                <tr>
                    <td align="right">
                        <label for="name">Semestre</label>
                    </td>
                    <td>
                        <select id="semestre" name="semestre">
                            <option value="0">Seleccione</option>
                    <?php for($i=0;$i<count($_semestre);$i++): ?>

                            <option value="<?php echo $_semestre[$i]["id"]; ?>" <?php if ($_semestre[$i]["id"] == $_POST["semestre"]) { echo "selected"; }?>><?php echo $_semestre[$i]["nombre"]; ?></option>

                    <?php endfor; ?>    
                        </select>   
                        <span class="campo-obligatorio">*</span>
                    </td>        
                </tr>  
                <tr align="center">  
                    <div class="pure-control-group">
                        <td  colspan="2" align="center">
                            <input type="button" class="btn btn-primary" value="Volver" onClick="window.location='seleccionar-tipo-de-calificacion'">
                            <input type="submit" class="btn btn-primary" value="Continuar" name="continuar">
                        </td>
                    </div>
                </tr>
            </tbody>
        </table>    
    </fieldset>
</form>
<?php endif; ?>