<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

?>
<script>
$(document).ready(function(){
   $("#semestre").change(function () {
       $("#semestre option:selected").each(function () {
            id = $(this).val();
            $.post("public/js/ajax/obtenerAsignaturaPorSemestre.php", { id: id }, function(data){
                $("#asignatura").html(data);//Destino
            });            
        });
   })
});
</script>
<div class="tema"><?php echo $tema; ?></div>

<?php
if ($notificacion) {
    echo $notificacion;
}

?>
<!--<div class="formulario" align="center">-->
<form class="pure-form pure-form-aligned" method="POST">
    <fieldset>
        <table class="pure-table pure-table-bordered" id="formulario">  
            <thead>
                <tr>
                    <th style="text-align: center;" colspan="2">Seleccionar Opción</th>
                </tr>
            </thead>
            <tbody>
<?php 
        if ($_periodoAcademico[0]["periodo_nota"] == '1') { 
              $disabled = "";
              $disabled_extra = "disabled";
              $cerrado = '<a href="cerrar-periodo-de-notas">Cerrar Período de Notas</a>';
            } else {
               $disabled = "disabled";
               $disabled_extra = "";
               $cerrado = '<span style="color:red;">Período de notas cerrado</span>'; 
            }
?>        
                <tr>
                    <td align="right">
                        <label for="asignatura">Asignatura</label>
                    </td> 
                    <td>
                    <select <?php echo $disabled; ?> id='asignatura' name='asignatura' <?php if($disabled == "disabled") {?>onClick="if(this.value != 0) {document.getElementById('extraordinario').disabled = true; document.getElementById('recuperativo').disabled = true; document.getElementById('cambio_nota').disabled = true;} else {document.getElementById('extraordinario').disabled = false; document.getElementById('recuperativo').disabled = false; document.getElementById('cambio_nota').disabled = false;};"<?php } ?>>
                        <option <?php echo $disabled; ?> value="0" >Seleccione</option>
            <?php for($i=0;$i<count($_asignatura); $i++): ?>
                        <option <?php echo $disabled; ?> value="<?php echo $_asignatura[$i]["id"]; ?>" <?php if($_asignatura[$i]["id"] == $_POST["asignatura"]) {echo "selected";}?>><?php echo  $_asignatura[$i]["asignatura"]. " => " . $_asignatura[$i]["codigo_seccion"]. " - " . $_asignatura[$i]["semestre"]; ?></option>
            <?php endfor; ?>
                    </select>
                        <?php 
                        if ($_SESSION["tipo_usuario"] == "Administrador"): 
                            echo "<BR>".$cerrado; 
                        endif;
                        ?>
                    </td>
                </tr>
        <?php ?>  
                <tr>
                    <td align="right">
                        <label for="email">Revisión</label>
                    </td> 
                    <td>
                        <input <?php echo $disabled_extra; ?> type="radio" id="recuperativo" name="opcion_nota" value="recuperativo">
                    </td>
                </tr>
        <?php if ($_SESSION["tipo_usuario"] == "Administrador"): ?>        
                <tr>
                    <td align="right">
                        <label for="email">Extraordinario</label>
                    </td> 
                    <td>
                        <input <?php echo $disabled_extra; ?> type="radio" id="extraordinario" name="opcion_nota" value="extraordinario">
                    </td>
                </tr> 
        <?php endif; ?>
        <?php if ($_SESSION["tipo_usuario"] == "Administrador"): ?>          
                <!--<tr>
                    <td align="right">
                        <label for="cambio_nota">Cambio Especial de Notas</label>
                    </td> 
                    <td>
                        <input <?php echo $disabled_extra; ?> type="radio" id="cambio_nota" name="opcion_nota" value="cambio_nota">
                    </td>
                </tr>-->
                <?php endif; ?>
        <?php if ($_SESSION["tipo_usuario"] == "Administrador"): ?>        
                <tr>
                    <td align="right">
                        <label for="email">Registro Especial de Notas</label>
                    </td> 
                    <td>
                        <input <?php //echo $disabled_extra; ?> type="checkbox" id="registro_especial" name="registro_especial" value="registro_especial" onClick="if(this.checked == true) {document.getElementById('asignatura').disabled=true;} else {document.getElementById('asignatura').disabled=false;}">
                    </td>
                </tr> 
        <?php endif; ?>                
                <tr align="center">  
                    <div class="pure-control-group">
                        <td  colspan="2" align="center">
                            <input type="button" class="btn btn-primary" value="Salir" onClick="window.location='<?php echo URLBASE; ?>inicio'">
                            <input type="submit" class="btn btn-primary" value="Continuar" name="continuar">
                        </td>
                    </div>
                </tr>
            </tbody>
        </table>    
    </fieldset>
</form>