<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

?>
<div class="tema"><?php echo $tema; ?></div>

<?php
if ($notificacion) {
    echo $notificacion;
}
?>
<form class="pure-form pure-form-aligned" method="POST" > 
    <fieldset>
        <table class="pure-table pure-table-bordered" id="formulario">
            <thead>
                <tr>
                    <th colspan="2">
                        <label>Datos del Estudiante</label>
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td align="right">
                        <label  for="tipo_dni">Tipo de Documento</label>
                    </td>                      
                    <td>
                        <select id="state" name="tipo_dni">
                            <option value="V" <?php if ($_POST["tipo_dni"] == "V") { echo "selected"; }?>>V</option>
                            <option value="E" <?php if ($_POST["tipo_dni"] == "E") { echo "selected"; }?>>E</option>
                        </select>
                        <span class='campo-obligatorio'>*</span>
                    </td>   
                </tr>  
                <tr>
                    <td align="right">
                        <label for="dni">Documento de Identidad</label>
                    </td>                      
                    <td>
                        <input id="dni" type="text" placeholder="Documento de Identidad" maxlength="8" name="dni" value="<?php echo $_POST["dni"]; ?>" autocomplete="off" class="solo-numero-entero">
                        <span class='campo-obligatorio'>*</span>
                    </td>
                </tr>
                <tr>
                    <td align="right">
                        <label for="password">Nombres</label>
                    </td>                      
                    <td>
                        <input type="text" placeholder="Nombres" maxlength="40" name="nombre" value="<?php echo $_POST["nombre"]; ?>" autocomplete="off" class="solo-letras-con-espacio-y-acentos">
                        <span class='campo-obligatorio'>*</span>
                    </td>    
                </tr>
                <tr>
                    <td align="right">
                        <label for="password">Apellidos</label>
                    </td>                      
                    <td>
                        <input type="text" placeholder="Apellidos" maxlength="40" name="apellido" value="<?php echo $_POST["apellido"]; ?>" autocomplete="off" class="solo-letras-con-espacio-y-acentos">
                        <span class='campo-obligatorio'>*</span>
                    </td>
                </tr>
                <tr>
                    <td align="right">
                        <label  for="state">Sexo</label>
                    </td>                      
                    <td>
                        <select id="state" name="sexo">
                            <option value="Femenino" <?php if ($_POST["sexo"] == "Femenino") { echo "selected"; }?>>Femenino</option>
                            <option value="Masculino" <?php if ($_POST["sexo"] == "Masculino") { echo "selected"; }?>>Masculino</option>
                        </select>
                        <span class='campo-obligatorio'>*</span>
                    </td>
                </tr>     
                <tr>
                    <td align="right">
                        <label for="email">Fecha de Nacimiento</label>
                    </td>                      
                    <td>
                        <input type="text" placeholder="dd/mm/aaaa" name="fecha_natal" maxlength="10" value="<?php echo $_POST["fecha_natal"]; ?>" class="fecha" autocomplete="off">
                        <span class='campo-obligatorio'>*</span>
                </td>
                </tr>
                <tr>
                    <td align="right">
                        <label for="email">Teléfono de Contacto</label>
                    </td>                      
                    <td>
                        <input type="text" id="telefono" placeholder="0294-321987465" name="telefono" maxlength="12" value="<?php echo $_POST["telefono"]; ?>" autocomplete="off" class="solo-numero-entero">
                        <span class='campo-obligatorio'>*</span>
                    </td>
                </tr>  
                <tr>
                    <td align="right">
                        <label for="email">Lugar de Nacimiento</label>
                    </td>                      
                    <td>
                        <input type="text" placeholder="Lugar de Nacimiento" name="lugar_nacimiento" maxlength="50" value="<?php echo $_POST["lugar_nacimiento"]; ?>" autocomplete="off" class="solo-letras-con-espacio-y-acentos">
                        <span class='campo-obligatorio'>*</span>
                    </td>
                </tr> 
                <tr>
                    <td align="right">
                        <label for="email">Estado</label>
                    </td>                      
                    <td>
                        <select name="estado">
                            <option value="0">Seleccione</option>
                <?php for ($i=0; $i<count($_estado); $i++): ?>
                            <option value="<?php echo $_estado[$i]["id"]; ?>" <?php if ($_POST["estado"] == $_estado[$i]["id"]) { echo "selected"; }?>>
                                <?php echo $_estado[$i]["estado"]; ?>
                            </option>
		<?php endfor; ?>
                        </select>
                
                        <span class='campo-obligatorio'>*</span>
                    </td>
                </tr> 
                <tr>
                    <td align="right">
                        <label for="email">Dirección de Habitación</label>
                    </td>                      
                    <td>
                        <input type="text" placeholder="Dirección de Habitación" name="direccion" maxlength="50" >
                        <span class='campo-obligatorio'>*</span>
                    </td>
                </tr>
                <tr>
                    <td colspan="2" align="center">
                        <input type="button" class="btn btn-primary" value="Salir" onClick="window.location='<?php echo URLBASE; ?>inicio'">
                        <input type="submit" class="btn btn-primary" value="Registrar" name="registrar">
                    </td> 
                </tr>
            </tbody>    
        </table>    
    </fieldset>
</form>
