<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

?>

<div class="tema"><?php echo $tema; ?></div>
<?php 
if (count($_periodoAcademico) == 0):
    echo $notificacion;
else:
if ($notificacion) {
    echo $notificacion;
}
?>
<form class="pure-form pure-form-aligned" method="POST">
    <fieldset>
        <table class="pure-table pure-table-bordered" id="formulario">  
            <thead>
                <tr>
                    <th colspan="2">Datos de Inscripción</th>
                </tr>
            </thead>
            <tbody>
                <tr>    
                    <td align="right">
                        <label for="name">Estudiante</label>
                    </td>
                    <td>
                        <input id="campo" type="text" placeholder="Documento de Identidad" maxlength="8" name="dni" value="<?php echo $_POST["dni"]; ?>" onKeyUp="autocompletadoEstudiante();" autocomplete="off" class="solo-numero-entero">
                        <span class='campo-obligatorio'>*</span>
                        <ul id="lista_dni"></ul>
                    </td>         
                </tr> 
                <tr>          
                    <td align="right">  
                        <label for="name">¿Posee certificación de notas?</label>
                    </td>
                    <td>
                        <label for="option-two" class="pure-radio">
                            <input  type="radio" name="equivalencia" value="S" <?php if ($_POST["equivalencia"] == "S") { echo "checked"; }?>>
                            Si
                        </label>
                            <label for="option-three" class="pure-radio">
                                <input checked type="radio" name="equivalencia" value="N" <?php if ($_POST["equivalencia"] == "N") { echo "checked"; }?>>
                                No
                            </label>
                    </td>  
                </tr>
                <tr align="center">  
                    <div class="pure-control-group">
                        <td  colspan="2" align="center">
                            <input type="button" class="btn btn-success" value="Cancelar" name="Salir" onClick="history.back();">
                            <input type="submit" class="btn btn-success" value="Continuar" name="continuar">
                        </td>
                    </div>
                </tr>
            </tbody>
        </table>    
    </fieldset>
</form>
<?php endif; ?>