<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

?>
<div class="tema"><?php echo $tema; ?></div>

<?php
if ($notificacion) {
    echo $notificacion;
}
?>

<form class="pure-form pure-form-aligned" method="POST">
    <fieldset>
        <table class="pure-table pure-table-bordered" id="formulario">  
            <thead>
                <tr>
                    <th style="text-align: center;" colspan="2">Selleción de la Institución</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <label  for="state">Institución Escolar</label>
                    </td>
                    <td>
                        <select id="institucion" name="institucion">
                <?php for ($i=0; $i<count($_institucion); $i++): ?>            
                                <option value="<?php echo $_institucion[$i]["id"]; ?>" <?php if ($_SESSION["institucion"] == $_institucion[$i]["id"]) { echo "selected"; }?>><?php echo $_institucion[$i]["nombre"]; ?></option>
                <?php endfor; ?>
                        </select>
                    </td>

                </tr>                
                <tr align="center">                       
                    <td  colspan="2" align="center">
                        <input type="reset" class="btn btn-primary" value="Volver" name="volver" onCLick="history.back();">  

                        <input type="submit" class="btn btn-primary" value="Continuar" name="continuar">
                    </td>
                </tr>          
            </tbody>
        </table>    
    </fieldset>
</form>