<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

?>
<div class="tema"><?php echo $tema; ?></div>
        <table style="margin:auto;">
            <tr>
                <td> 
                    <form class="pure-form pure-form-aligned" method="POST"  onSubmit="return validarCampoBuscar('semestre')">
                        <select name="semestre" id="semestre">
                            <option value="0">Semestre</option>
                <?php for ($i=0; $i<count($_semestre); $i++): ?>                            
                            <option <?php echo $_semestre[$i]["id"]; ?>><?php echo $_semestre[$i]["nombre"]; ?></option>
                <?php endfor; ?>
                        </select>
                        <input type="submit" value="Buscar" class="btn btn-default">
                     </form>
                        <ul id="lista_dni"></ul>
                </td>
            </tr>
        </table>    
<br>
<table class="pure-table pure-table-horizontal" style="margin:auto;">
    <thead>
        <tr>
            <th>Docente</th>
            <th>Asignatura</th>
            <th>Sección</th>
            <th>Cupos</th>
            <th>Horas</th>
        </tr>
    </thead>

    <tbody>
<?php 
	for ($i=0; $i<COUNT($_horarioAsignatura); $i++):

        echo "<tr>
                <td>" . $_horarioAsignatura[$i]["tipo_dni"]  . "-" . $_horarioAsignatura[$i]["dni"] . "</td>
                <td>" . $_horarioAsignatura[$i]["nombre"] . "</td>
                <td>" . $_horarioAsignatura[$i]["codigo_seccion"] . "</td>
                    <td>" . $_horarioAsignatura[$i]["cupos"] . "</td>
                <td title='Horario Asignado' align=center>
                    <form method='POST' action='" . URLBASE . "consultar-horario-de-asignatura'>
                            <input type='hidden' name='pagina_referencia' value='" . $_GET["pagina"] ."'>
                            <input type='hidden' name='id_horario' value='" . $_horarioAsignatura[$i]["id"] ."'>
                        <input type='image'src='" . URLBASE . "public/img/asignar.png'/>
                    </form>
                </td>
            </tr>";
	endfor; ?>
    </tbody>
</table>
<div class='paginador' align='center' >
        <ul>
            <li>
            <?php if($params['primero']):	?>
                <a  class='parametro'  href="<?php echo URLBASE . $_GET["vista"]; ?>/pagina/<?php echo $params['primero']; ?>">
                <input type="button" value="Primera" class="btn-enabled" />
                </a>
            <?php	else: ?>
                    <input type="button" value="Primera" disabled class="btn-disabled" />
            <?php	endif; ?>

            </li>
            <li>
            <?php if($params['anterior']):	?>
                <a  class='parametro'  href="<?php echo URLBASE . $_GET["vista"]; ?>/pagina/<?php echo $params['anterior']; ?>">
                <input type="button" value="&larr; Anterior"  class="btn-enabled" />
                </a>
            <?php	else: ?>
                <input type="button" value="&larr; Anterior" disabled class="btn-disabled" />
            <?php	endif; ?>
            </li>
            <li>
            <?php if($params['siguiente']):	?>
                <a  class='parametro'  href="<?php echo URLBASE . $_GET["vista"]; ?>/pagina/<?php echo $params['siguiente']; ?>">
                <input type="button" value="Siguiente &rarr;" class="btn-enabled" />
                </a>	
            <?php	else: ?>
                <input type="button" value="Siguiente &rarr;" class="btn-disabled" />
            <?php	endif; ?>
            </li>
            <li>
            <?php if($params['ultimo']):	?>
                <a  class='parametro'  class='parametro' href="<?php echo URLBASE . $_GET["vista"]; ?>/pagina/<?php echo $params['ultimo']; ?>">
                <input type="button" value="Última" class="btn-enabled" />
                </a>
            <?php	else: ?>
                <input type="button" value="Última" class="btn-disabled" />
            <?php	endif; ?>
            </li>
        </ul>
    </div>
<?php if($pagina < 2): ?>
    <div id='icono-papelera-y-regresar'>
        <div id='sub-icono'>
            <a href='javascript:void();' onClick="window.location='<?php echo URLBASE; ?>consultar-asignatura';" title='Volver Atrás'>
                <div id='imagen-volver'></div>
                <div id='nombre-icono'>Volver Atrás</div>
            </a>
        </div>
    </div>
<?php endif; ?>