<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

?>

<div class="tema"><?php echo $tema; ?></div>

<?php
if ($notificacion) {
    echo $notificacion;
}

?>
<!--<div class="formulario" align="center">-->
<form class="pure-form pure-form-aligned" method="POST">
    <fieldset>
        <table class="pure-table pure-table-bordered" id="formulario">  
            <thead>
                <tr>
                    <th style="text-align: center; color:red;" colspan="2">Confirmar Cierre del Período de Notas</th>
                </tr>
            </thead>
            <tbody>
                <tr>
          
                    <td align="right">
                        <label for="email">Período De Notas Actual</label>
                    </td> 
                    <td>
                        <input readonly id="codigo" type="text" placeholder="Período Escolar" maxlength="20" name="periodo"  value="<?php echo $_periodoAcademico[0]["periodo_academico"]; ?>">
                    </td>
         
                </tr>            
                <tr>
                    <td align="center" colspan="2">
                        <span style="color:blue;">¿Está seguro que desea cerrar el período de notas actual?<br>Se recuerda que no podrá deshacer los cambios.</span>
                    </td> 
                </tr>

                <tr align="center">  

                    <td  colspan="2" align="center">
                        <input type="button" class="btn btn-danger" value="Cancelar" onClick="history.back();">  

                        <input type="submit" class="btn btn-danger" value="Confirmar" name="confirmar">
                    </td>

                </tr>
            </tbody>
        </table>    
    </fieldset>
</form>