<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

?>
<div class="tema"><?php echo $tema; ?></div>

<?php 
/*
if ($inscrito == 0):
    echo $notificacion;    
else:*/
?>
<table class="pure-table pure-table-horizontal" style="margin:auto;">
    <thead>
        <tr>
            <th>Documento</th>
            <th>Nombre y Apellido</th>
            <th>Sexo</th>
            <th>Edad</th>
            <th>PDF</th>
            
        </tr>
    </thead>

    <tbody>
<?php 
	for ($i=0; $i<COUNT($_estudiante); $i++):
        echo "<tr>
                <td>" . $_estudiante[$i]["tipo_dni"] . "-" . $_estudiante[$i]["dni"] ."</td>
                <td>" . $_estudiante[$i]["nombre"] . " " . $_estudiante[$i]["apellido"] . "</td>
                <td>" . $_estudiante[$i]["sexo"] . "</td>
                <td > " . AsistenteBasico::obtenerEdad($_estudiante[$i]["fecha_natal"]) . " años</td>

                <td title='PDF' align=center>
                    <form method='POST' action='" . $_SESSION["url_constancia"] . "' target='_blank'>
                        <input type='hidden' name='dni_estudiante' value='" . $_estudiante[$i]["dni"] ."'>
                        <input type='image' src='" . URLBASE . "public/img/pdf.png'/>
                    </form>
                </td>
            </tr>";
	endfor; ?>
    </tbody>
</table>

<div class="contenido" >
    <div id="dialogo_estudiante" class="ventana" title="Detalle del Estudiante">
    </div>
</div>	
<?php //endif; ?>
    <div id='icono-papelera-y-regresar'>
        <div id='sub-icono'>
            <a href='javascript:void();' onClick="history.back();" title='Volver Atrás'>
                <div id='imagen-volver'></div>
                <div id='nombre-icono'>Volver Atrás</div>
            </a>
        </div>
    </div>