<?php
ob_start();
//$_SESSION["emision_de_constancia"] = true;
$nombre_emision = explode(" ", $_SESSION["nombre_sesion"]);
$apellido_emision = explode(" ", $_SESSION["apellido_sesion"]);
?>
<style type="text/css">
    *{       
        font-size: 10pt;
        line-height: 1.5;
        font-family: arial;
        color:#000;
        margin:0;
        padding:0;
    }
    .banner{
        width: auto;
        margin: auto;
        text-align: center;
        margin-top: 30px;
        padding: 0; 
        
    }
    .banner img {
        width: 850;
        height: auto;
    }
    #cuerpo {
        margin: auto;
        width: 100%;
        height:auto;
        border:0px;        
    }
    #tema {
        font-size: 12pt;
        margin: auto;
        margin-top: 15px;
        margin-bottom: 20px;
        text-align:center;
        font-weight: bold;
    }
	table.datos-personales {
            margin:auto;
		width: 100%;        
        border-collapse: collapse; 
		
	}
	.datos-personales td, .datos-personales th {
		width:50%;
		border:1px solid #cbcbcb;        
        padding: 4px 4px;
		
	}
	.datos-personales th.titulo {
		background: #9A121B;
		color:white;
	}
    table.horario {
        margin: auto;
	width: 100%;        
        border-collapse: collapse; 		
    }
    .horario td {
        width: 20%;
        border:1px solid #cbcbcb;        
        padding: 4px 2px;
        display: table-cell;
	vertical-align: middle;
    }    
    .subtitulo-tabla {
        background: #9A121B;
        color: white;
        font-weight: bold;
        text-transform:none;
    }
    .descripcion-tabla { 
        background: #f9f9f9;
        font-weight: bold;
    }
 
    #pie-de-pagina {        
        heigh:auto;        
        margin:auto;
        font-size: 10pt;       
    }
    #pagina {  
        position: relative;
        font-size: 10pt;
        left:60px;
        text-align: left;
    }
    #datos-emision {
        position: relative;
        top:-20px;
        font-size: 10pt;
        text-align: right;
        right:60px;
    }
  </style>

<page backtop='30mm' backbottom='20mm' backleft='20mm' backright='20mm'>
    <page_header>
        <div class="banner" ><img src="<?php echo URLBASE; ?>/public/img/<?php echo $institucion["img_reporte"]; ?>" /></div>
    </page_header>
    <page_footer>
        <div id="pie-de-pagina">
            <div id="pagina">Página [[page_cu]]/[[page_nb]]</div>
            <div id="datos-emision">Emitido por <?php echo $nombre_emision[0] . " " . $apellido_emision[0];  ?>, el <?php echo date("d/m/Y"); ?> a las <?php echo date('h:i:s A'); ?></div> 
        </div>
    </page_footer>
    <div id="cuerpo">
        <div id="tema"><?php echo $tema ." " . $tipoEducacion; ?></div>        
        <table class="datos-personales">
            <tr>
                <th colspan="2" align="center" class="titulo">Datos del Docente</th>
            </tr>
            <tr>
                <th>Nombres y Apellidos</th>
                <td><?php echo $_horarioDocente[0]["docente"];?></td>
            </tr>
            <tr>
                <th>Documento de Identidad</th>
                <td><?php echo $_horarioDocente[0]["dni_docente"];?></td>
            </tr>
            <tr>
                <th>Período Escolar</th>
                <td><?php echo $_periodo[0]["periodo_academico"];?></td>
            </tr>
        </table>
		<br>
		<table class="horario">
            <tr align="center">                
                <td class="subtitulo-tabla">Asignatura</td>
                <td class="subtitulo-tabla">Semestre</td>
                <td class="subtitulo-tabla">Hora</td>  
                <td class="subtitulo-tabla">Sección</td>                            
                <td class="subtitulo-tabla">Aula</td>               
            </tr>
<?php 
$dia[] = 0;
for ($i=0; $i<count($_horarioDocente); $i++): 
       $_dia = $_horarioDocente[$i]["dia"];
       if($_dia == 1)
            $dia["lun"]++;
       if($_dia == 2)
            $dia["mar"]++;
       if($_dia == 3)
            $dia["mie"]++;
       if($_dia == 4)
            $dia["jue"]++;
       if($_dia == 5)
            $dia["vie"]++;
endfor;

    for ($i=0; $i<count($_horarioDocente); $i++): 
?>
            <tr align="center" >                
                
                <td><?php echo $_horarioDocente[$i]["asignatura"]; ?></td>   
                <td><?php echo $_horarioDocente[$i]["semestre"]; ?></td>   
                <td><?php echo AsistenteBasico::obtenerDiaDeLaSemana($_horarioDocente[$i]["dia"])."<BR>"; ?><?php echo AsistenteBasico::convertirHoraA12H($_horarioDocente[$i]["hora_inicio"]) . " - " . AsistenteBasico::convertirHoraA12H($_horarioDocente[$i]["hora_salida"]); ?></td>
                <td><?php echo $_horarioDocente[$i]["seccion"]; ?></td>
                <td><?php echo $_horarioDocente[$i]["aula"]; ?></td>
            </tr>
<?php endfor; ?>
        </table>

    </div>


    
  
</page>
<?php
     $contenido = ob_get_clean();
     $salida = "Carga_horaria_" . $_horarioDocente[0]["dni_docente"] . ".pdf";
ob_clean();
    try
    {
    $html2pdf = new HTML2PDF('L','Letter','es','true','UTF-8');
    $html2pdf->setDefaultFont('Arial');
    $html2pdf->pdf->SetDisplayMode('fullpage');
    $html2pdf->writeHTML($contenido, isset($_GET['vuehtml']));
    $html2pdf->Output($salida);


    }
    catch(HTML2PDF_exception $e) {
        echo $e;
        exit;
    }

