<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

?>
<div class="tema"><?php echo $tema; ?></div>

<?php
if ($notificacion) {
    echo $notificacion;
}

?>
<form class="pure-form pure-form-aligned" method="POST">
    <fieldset>
        <table class="pure-table pure-table-bordered" id="formulario">  
            <thead>
                <tr>
                    <th style="text-align: center;" colspan="2">Datos para el Reporte</th>
                </tr>
            </thead>
            <tbody>
                <tr>    
                    <td align="right">
                        <label for="name">Estudiante</label>
                    </td>
                    <td>
                        <input id="campo" type="text" placeholder="Documento de Identidad" maxlength="8" name="dni" value="<?php echo $_POST["dni_estudiante"]; ?>" onKeyUp="autocompletadoEstudiante();" autocomplete="off">
                        <span class='campo-obligatorio'>*</span>
                         <ul id="lista_dni"></ul>
                    </td>         
                </tr>
                <tr>
                    <td align="right">
                        <label for="name">Tipo de Solicitud</label>
                    </td>
                    <td>
                        <select id="tipo_constancia" name="tipo_constancia">
                            <option value="0">Seleccione</option>                            
                            <option value="notas" <?php if ($_POST["tipo_constancia"] == "notas") { echo "selected";}?>>Certificación de Notas</option>
				<?php if (count($_periodoAcademico)>0): ?>				
                            <option value="estudio" <?php if ($_POST["tipo_constancia"] == "estudio") { echo "selected";}?>>Constancia de Estudio</option>
				<?php endif; ?>			
                            <option value="horario" <?php if ($_POST["tipo_constancia"] == "horario") { echo "selected";}?>>Horario de Clases</option>
                            <option value="record" <?php if ($_POST["tipo_constancia"] == "record") { echo "selected";}?>>Record de Notas</option>
                        </select>
                        <span class='campo-obligatorio'>*</span>
                    </td>       
                </tr>
              
    
                <tr align="center">
                    <td  colspan="2" align="center">
                        <input type="button" class="btn btn-primary" value="Salir" onClick="window.location='<?php echo URLBASE; ?>inicio'">
                        <input type="submit" class="btn btn-primary" value="Buscar" name="enviar">
                    </td>      
                </tr>
            </tbody>
        </table>    
    </fieldset>
</form>
