<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

?>
<div class="tema"><?php echo $tema; ?></div>

<?php
if ($notificacion) {
    echo $notificacion;
}
?>
<form class="pure-form pure-form-aligned" method="POST">
    <fieldset>
        <input type="hidden" value="<?php $_usuario[0]["usuario"]; ?>" name="usuario">
        <input type="hidden" value="<?php echo $_POST["pagina_referencia"] ;?>" name="pagina_referencia">
        <table class="pure-table pure-table-bordered" id="formulario">
            <thead>
                <tr>
                    <th colspan="2">
                        <label>Datos del Usuario</label>
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <label for="usuario">Usuario</label>
                    </td>
                    <td>
                        <input id="name" type="text" placeholder="Usuario" maxlength="20" name="usuario" value="<?php echo $_usuario[0]["usuario"]; ?>" readonly>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="email">Correo Electrónico</label>
                    </td>
                <td>
                    <input id="email" type="email" placeholder="Correco Electrónico" maxlength="50" name="email"  value="<?php echo $_usuario[0]["email"]; ?>">
                </td>    
                </tr>
                <tr>
                    <td>
                        <label  for="tipo_usuario">Tipo de Usuario</label>
                    </td>
                    <td>
                        <select id="state" name="tipo_usuario">
                            <option value="0">Seleccione</option>
                            <option value="Administrador" <?php if ($_usuario[0]["tipo_usuario"] == "Administrador") { echo "selected"; }?>>Administrador</option>
                            <option value="Secretariado" <?php if ($_usuario[0]["tipo_usuario"] == "Secretariado") { echo "selected"; }?>>Secretariado</option>
                            <option value="Docente" <?php if ($_usuario[0]["tipo_usuario"] == "Docente") { echo "selected"; }?>>Docente</option>
                        </select>
                    </td>
                </tr>        

                <tr>
                    <td colspan="2" align="center">
                        <input type="button" class="btn btn-primary" value="Cancelar" name="Salir" onClick="history.back();">
                        <input type="submit" class="btn btn-primary" value="Guardar" name="editar">
                    </td>
                </tr>
            </tbody>
        </table>
    </fieldset>
</form>
