<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

?>

<div class="tema"><?php echo $tema; ?></div>

<?php
if($notificacion) {
    echo $notificacion;
}
if ($recuperacion == 1) {
    echo '<div class="alert alert-success" role="alert" style="margin:auto;width: 40em;">
          <strong>¡Muy bien!</strong> Su nueva contraseña es: <b>' . $nuevaContrasenia . '</b>
          <a style="float:right;"href="' . URLBASE . '" title="Iniciar Sesión">Iniciar Sesión</a>
                  
</div>';
 
           
}
if ($recuperacion != 1):
?>
<!--<div class="formulario" align="center" >-->
<form class="pure-form pure-form-aligned" method="POST">
    <fieldset>
        
        <table class="pure-table pure-table-bordered" id="formulario">
            <thead>
                <tr>
                    <th colspan="2">Datos de Recuperación</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td align="right">
                        <label for="name">Pregunta Secreta</label>
                    </td>
                    <td>
                        <input readonly autocomplete="off" type="text" placeholder="Documento de Identidad" maxlength="8" name="dni" value="<?php echo $_usuario[0]["pregunta_secreta"]; ?>">
                    </td>
                </tr>
                <tr>  
                    <td align="right">
                        <label for="name">Respuesta Secreta</label>
                    </td>
                    <td>
                        <input autocomplete="off" type="password" placeholder="Respuesta Secreta" maxlength="40" name="respuesta" value="<?php echo $_POST["respuesta"]; ?>">
                    </td>
                    
                </tr>             
                <tr>
                    <td  colspan="2" align="center">
                        <input type="button" class="btn btn-primary" value="Salir" onClick="window.location='<?php echo URLBASE; ?>'">
                        <input type="submit" class="btn btn-primary" value="Enviar" name="enviar">
                    </td>                   
                </tr>
            </tbody>  
        </table>
    </fieldset>
</form>
<?php endif; ?>