<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

?>
<div class="tema"><?php echo $tema; ?></div>

<?php
if ($notificacion) {
    echo $notificacion;
}
?>
<!--<div class="formulario" align="center" >-->
<form class="pure-form pure-form-aligned" method="POST">
    <fieldset>
        
        <table class="pure-table pure-table-bordered" id="formulario">
            <thead>
                <tr>
                    <th colspan="2">Datos del Usuario</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td align="right">
                        <label for="name">Documento</label>
                    </td>
                    <td>
                        <input id="campo" onKeyUp="autocompletadoUsuario();" autocomplete="off" type="text" placeholder="Documento de Identidad" maxlength="8" name="dni" value="<?php echo $_POST["dni"]; ?>" class="solo-numero-entero">
                        <ul id="lista_dni"></ul>
                        <span class='campo-obligatorio'>*</span>
                    </td>
                </tr>
                <tr>  
                    <td align="right">
                        <label for="name">Usuario</label>
                    </td>
                    <td>
                        <input type="text" placeholder="Usuario" maxlength="20" name="usuario" value="<?php echo $_POST["usuario"]; ?>" class="solo-albabeto-espaniol-sin-espacio">
                        <span class='campo-obligatorio'>*</span>
                    </td>
                </tr>
  
                <!--<tr>     
                    <td align="right">
                        <label for="password">Contraseña</label>
                    </td>
                    <td>
                        <input id="password" type="password" placeholder="Contraseña" maxlength="32" name="contrasenia" value="<?php echo $_POST["contrasenia"]; ?>">
                        <span class='campo-obligatorio'>*</span>
                    </td>         
                </tr>    
                <tr>         
                    <td align="right">
                        <label for="password">Confirmar Contraseña</label>
                    <td>
                        <input id="password" type="password" placeholder="Confirmar Contraseña" maxlength="32" name="contrasenia2" value="<?php echo $_POST["contrasenia2"]; ?>">
                        <span class='campo-obligatorio'>*</span>
                    </td>
                </tr>-->
    
                <tr> 
                    <td align="right">
                        <label for="email">Correo Electrónico</label>
                    </td> 
                    <td>
                        <input id="email" type="email" placeholder="Correco Electrónico" maxlength="50" name="email"  value="<?php echo $_POST["email"]; ?>">
                        <span class='campo-obligatorio'>*</span>
                    </td>
                </tr>
                <tr> 
                    <td align="right">
                        <label for="email2">Confirmar Correo Electrónico</label>
                    </td> 
                    <td>
                        <input id="email2" type="text" placeholder="Confirmar Correo Electrónico" maxlength="50" name="email2"  value="<?php echo $_POST["email2"]; ?>">
                        <span class='campo-obligatorio'>*</span>
                    </td>
                </tr>
                <!--<tr> 
                    <td align="right">
                        <label for="pregunta">Pregunta Secreta</label>
                    </td> 
                    <td>
                        <input id="email2" type="text" placeholder="Pregunta Secreta" maxlength="40" name="pregunta"  value="<?php echo $_POST["pregunta"]; ?>">
                        <span class='campo-obligatorio'>*</span>
                    </td>
                </tr>
                <tr> 
                    <td align="right">
                        <label for="respuesta">Respuesta Secreta</label>
                    </td> 
                    <td>
                        <input id="respuesta" type="text" placeholder="Respuesta Secreta" maxlength="40" name="respuesta"  value="<?php echo $_POST["respuesta"]; ?>">
                        <span class='campo-obligatorio'>*</span>
                    </td>
                </tr>-->
                <tr>
                    <td align="right">
                        <label  for="state">Tipo de Usuario</label>
                    </td>
                    <td>
                        <select id="state" name="tipo_usuario">
                            <option value="0">Seleccione</option>
                            <option value="Administrador" <?php if ($_POST["tipo_usuario"] == "Administrador") { echo "selected"; }?>>Administrador</option>
                            <option value="Secretariado" <?php if ($_POST["tipo_usuario"] == "Secretariado") { echo "selected"; }?>>Secretariado</option>
                            <option value="Docente" <?php if ($_POST["tipo_usuario"] == "Docente") { echo "selected"; }?>>Docente</option>
                        </select>
                        <span class='campo-obligatorio'>*</span>
                    </td>      
                </tr>
             
                <tr>
                    <td  colspan="2" align="center">
                        <input type="button" class="btn btn-primary" value="Salir" onClick="window.location='<?php echo URLBASE; ?>inicio'">
                        <input type="submit" class="btn btn-primary" value="Registrar" name="registrar">
                    </td>                   
                </tr>
            </tbody>  
        </table>
    </fieldset>
</form>
<!--</div>
-->