<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

?>
<div class="tema"><?php echo $tema; ?></div>

<?php
if ($notificacion) {
    echo $notificacion;
}

?>
<form class="pure-form pure-form-aligned" method="POST">
    <fieldset>
        <table class="pure-table pure-table-striped" id="formulario">  

            <tbody>
                <tr align="left">    
                    <td>
                        <p for="name">
                            <b>Nombre:</b> SIGARH
                            <br>
                            <b>Versión:</b> 1.0 BETA
                            <br>
                            <b>Lanzamiento:</b> Julio de 2015
                            <br>
                            <br>
                            <b>Diseño y Desarrollo por:</b>
                            <br>
                           Miguel Ángel Salazar Castillo
                            <br>
                            <b>En colaboración con:</b>
                            <br>
                           Elda Bello, Rauly Moreno, Jesús Indriago, Luis Subero y Luis Reyes
                           <BR>
                           <BR>
                           <k>Producto construido bajo software libre con estándares abiertos,
                               en cumpliento con la Ley de Infogobierno (2014).</k>
                        </p>
                                                
                    </td>                   
                </tr>             
            </tbody>
        </table>    
    </fieldset>
</form>