<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

?>
<!--<div class="tema"><?php echo $tema; ?></div>-->

<?php
if ($notificacion) {
    echo $notificacion;
}

?>
<form class="pure-form pure-form-aligned" method="POST">
    <fieldset>
        <div style="margin:auto; text-align: center; margin-top:3.1em; font-weight: bold; font-size: 14pt; color:gray;">
            ..::Sistema de Gestión Académica CEA "República de Haití"::..
        </div>   
        <div style="margin:auto; text-align: center; margin-top:2em;">
            <img style="width:360px; height:400px;" src="<?php echo URLBASE; ?>public/img/insignea.png">
        </div>
        
    </fieldset>
</form>