<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

?>
<div class="tema"><?php echo $tema; ?></div>

<?php
if ($notificacion) {
    echo $notificacion;
}
?>
<form class="pure-form pure-form-aligned" method="POST">
    <fieldset>
        <input type="hidden" value="<?php echo $_responsable[0]["dni"]; ?>" name="dni_responsable">
        <input type="hidden" value="<?php echo $_POST["pagina_referencia"] ;?>" name="pagina_referencia">
        <table class="pure-table pure-table-bordered" id="formulario">
            <thead>
                <tr>
                    <th colspan="2">
                        <label>Datos del Reponsable de Inscripción</label>
                    </th>
                </tr>
            </thead>
            <tbody>    
                <tr>
                    <td>
                        <label  for="state">Tipo de Documento</label>
                    </td>
                    <td>    
                        <select id="state" name="tipo_dni">
                            <option value="V" <?php if ($_responsable[0]["tipo_dni"] == "V") { echo "selected"; }?>>V</option>
                            <option value="E" <?php if ($_responsable[0]["tipo_dni"] == "E") { echo "selected"; }?>>E</option>
                        </select>
                    </td>    
                </tr>  
                <tr>
                    <td>
                        <label for="name">Documento de Identidad</label>
                    </td>
                    <td>
                        <input id="name" type="text" placeholder="Documento de Identidad" maxlength="8" name="dni" value="<?php echo $_responsable[0]["dni"]; ?>">
                    </td>
                </tr>

                <tr>
                    <td>
                        <label for="password">Nombres</label>
                    </td>
                    <td>
                        <input id="password" type="text" placeholder="Nombres" maxlength="40" name="nombre" value="<?php echo $_responsable[0]["nombre"]; ?>">
                    </td>
                </tr>

                <tr>
                    <td>
                        <label for="password">Apellidos</label>
                    </td>
                    <td>
                        <input id="password" type="text" placeholder="Apellidos" maxlength="40" name="apellido" value="<?php echo $_responsable[0]["apellido"]; ?>">
                    </td>    
                </tr>
                <tr>
                    <td>
                        <label  for="state">Sexo</label>
                    </td>
                    <td>
                        <select id="state" name="sexo">
                            <option value="Femenino" <?php if ($_responsable[0]["sexo"] == "Femenino") { echo "selected"; }?>>Femenino</option>
                            <option value="Femenino" <?php if ($_responsable[0]["sexo"] == "Femenino") { echo "selected"; }?>>Masculino</option>
                        </select>
                    </td>    
                </tr>     
                <tr>
                    <td>
                        <label for="email">Fecha de Nacimiento</label>
                    </td>
                    <td>
                        <input type="text" placeholder="dd/mm/aaaa" name="fecha_natal"  maxlength="10" value="<?php echo AsistenteBasico::convertirFechaDdMmAaaa($_responsable[0]["fecha_natal"]); ?>" id="fecha" >
                    </td>
                </tr>       
                <tr>
                    <td colspan="2" align="center"> 
                        <input type="reset" class="btn btn-primary" value="Salir" name="Salir" onClick="history.back();">
                        <input type="submit" class="btn btn-primary" value="Editar" name="editar">
                    </td>
                </tr>
            </tbody>
        </table>
    </fieldset>
</form>

